import React, { useState } from 'react';
import { Brain, Sparkles, Send, ArrowRight } from 'lucide-react';
import { AI_DIGEST, AI_QA_RESPONSES } from '../mockData';

function formatMarkdown(text) {
  return text.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>').replace(/\n/g, '<br/>');
}

export default function AIDigest() {
  const [question, setQuestion] = useState('');
  const [qas, setQas] = useState([]);
  const [thinking, setThinking] = useState(false);
  const [selectedSuggestion, setSelectedSuggestion] = useState(null);

  const SUGGESTED = [
    'Which products did Diamond Palace order most?',
    'Show me slow moving inventory',
    'Who are my inactive dealers?',
    'What is performing best this month?',
  ];

  const handleAsk = (overrideQ) => {
    const q = overrideQ || question;
    if (!q.trim()) return;
    setThinking(true);
    setSelectedSuggestion(q);
    const normalized = q.toLowerCase().replace(/[?!]/g, '').trim();

    setTimeout(() => {
      const answer = AI_QA_RESPONSES[normalized] ||
        'Based on current data: **Mangalsutra Diamond** and **Lakshmi Gold Pendant** are your top performers this month by order count. Revenue is tracking 18% above last year. Would you like a breakdown by category or by dealer?';
      setQas(prev => [{ q, a: answer }, ...prev]);
      setQuestion('');
      setThinking(false);
    }, 1500);
  };

  return (
    <div className="page-container fade-in">
      <div className="flex items-center gap-3 page-header">
        <Brain size={24} color="var(--purple)"/>
        <div>
          <div className="page-title">AI Business Digest</div>
          <div className="page-subtitle">Weekly AI-generated summary + ask questions about your business data</div>
        </div>
        <span className="ai-badge ml-auto"><Sparkles size={10}/> GPT-4o Powered</span>
      </div>

      {/* Weekly Digest Card */}
      <div className="ai-digest-card mb-6">
        <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 16 }}>
          <span style={{ fontSize: '1.4rem' }}>📊</span>
          <div>
            <div style={{ fontWeight: 800, fontSize: '1.1rem' }}>Weekly Business Digest</div>
            <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>Period: {AI_DIGEST.period} · Generated by AI</div>
          </div>
        </div>

        {/* Highlights */}
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 12, marginBottom: 20 }}>
          {AI_DIGEST.highlights.map((h, i) => (
            <div key={i} style={{ textAlign: 'center', padding: '14px', background: 'rgba(0,0,0,0.25)', borderRadius: 12, border: '1px solid rgba(255,255,255,0.05)' }}>
              <div style={{ fontSize: '1.6rem', fontWeight: 800, color: h.up ? 'var(--green)' : 'var(--red)' }}>{h.value}</div>
              <div style={{ fontSize: '0.68rem', color: 'var(--text-muted)', marginTop: 3 }}>{h.label}</div>
              <div style={{ fontSize: '0.72rem', color: h.up ? 'var(--green)' : 'var(--red)', fontWeight: 700, marginTop: 2 }}>{h.change}</div>
            </div>
          ))}
        </div>

        {/* AI Summary Text */}
        <div style={{ background: 'rgba(0,0,0,0.2)', borderRadius: 12, padding: 20, fontSize: '0.9rem', color: 'var(--text-secondary)', lineHeight: 1.8 }}
          dangerouslySetInnerHTML={{ __html: formatMarkdown(AI_DIGEST.summary) }}
        />

        <div style={{ marginTop: 14, display: 'flex', gap: 10 }}>
          <button className="btn btn-secondary btn-sm"><ArrowRight size={13}/> Share via Email</button>
          <button className="btn btn-ghost btn-sm">Download PDF</button>
        </div>
      </div>

      {/* Q&A Section */}
      <div className="ai-section">
        <div style={{ fontWeight: 800, fontSize: '1.05rem', marginBottom: 6 }}>
          Ask Your Business Data
        </div>
        <div style={{ fontSize: '0.82rem', color: 'var(--text-muted)', marginBottom: 16 }}>
          Ask any question about your inventory, orders, or dealer activity in plain English.
        </div>

        {/* Suggestions */}
        <div style={{ display: 'flex', flexWrap: 'wrap', gap: 8, marginBottom: 16 }}>
          {SUGGESTED.map(s => (
            <button key={s} className={`filter-chip ${selectedSuggestion === s ? 'active' : ''}`} onClick={() => handleAsk(s)}>
              {s}
            </button>
          ))}
        </div>

        {/* Input */}
        <div style={{ display: 'flex', gap: 10, marginBottom: 20 }}>
          <input
            className="form-input"
            placeholder='e.g. "Which products did Diamond Palace order most this quarter?"'
            value={question}
            onChange={e => setQuestion(e.target.value)}
            onKeyDown={e => e.key === 'Enter' && handleAsk()}
            style={{ flex: 1 }}
          />
          <button className="btn btn-primary" onClick={() => handleAsk()} disabled={thinking || !question.trim()}>
            <Send size={14}/> {thinking ? 'Thinking...' : 'Ask AI'}
          </button>
        </div>

        {/* Thinking indicator */}
        {thinking && (
          <div style={{ display: 'flex', alignItems: 'center', gap: 10, padding: '12px 16px', background: 'rgba(155,111,232,0.1)', borderRadius: 8, marginBottom: 12 }}>
            <Brain size={15} color="var(--purple)"/>
            <span style={{ fontSize: '0.83rem', color: 'var(--purple)' }}>AI is analysing your business data...</span>
            <div style={{ display: 'flex', gap: 4, marginLeft: 'auto' }}>
              {[0,1,2].map(i => (
                <div key={i} style={{ width: 6, height: 6, borderRadius: '50%', background: 'var(--purple)', animation: `pulse 1.2s ${i*0.2}s infinite` }}/>
              ))}
            </div>
          </div>
        )}

        {/* Q&A History */}
        {qas.map((item, i) => (
          <div key={i} style={{ marginBottom: 16 }}>
            <div style={{ display: 'flex', gap: 10, marginBottom: 8 }}>
              <div style={{ width: 28, height: 28, borderRadius: '50%', background: 'var(--bg-surface)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '0.75rem', color: 'var(--text-muted)', flexShrink: 0 }}>You</div>
              <div style={{ background: 'var(--bg-surface)', border: '1px solid var(--border-default)', borderRadius: '4px 12px 12px 12px', padding: '10px 14px', fontSize: '0.875rem', color: 'var(--text-primary)' }}>
                {item.q}
              </div>
            </div>
            <div style={{ display: 'flex', gap: 10 }}>
              <div style={{ width: 28, height: 28, borderRadius: '50%', background: 'linear-gradient(135deg, var(--purple), var(--blue))', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '0.7rem', flexShrink: 0 }}>🤖</div>
              <div style={{ background: 'linear-gradient(135deg, rgba(155,111,232,0.12), rgba(91,140,245,0.12))', border: '1px solid rgba(155,111,232,0.2)', borderRadius: '4px 12px 12px 12px', padding: '12px 16px', fontSize: '0.875rem', color: 'var(--text-secondary)', lineHeight: 1.7 }}
                dangerouslySetInnerHTML={{ __html: formatMarkdown(item.a) }}
              />
            </div>
          </div>
        ))}

        {qas.length === 0 && !thinking && (
          <div style={{ textAlign: 'center', padding: '30px 20px', color: 'var(--text-muted)', fontSize: '0.85rem' }}>
            Ask a question above or pick a suggestion to get started
          </div>
        )}
      </div>
    </div>
  );
}
